# Generated by Django 3.2.4 on 2021-07-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='PhoneNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
